LANG_UA = {
    # Заголовки та тексти
    "(нм)": "(nm)",
    "[Сумський державний університет](https://sumdu.edu.ua)": "[Sumy State University](https://int.sumdu.edu.ua/en/)",
    "[Контакт](https://pom.sumdu.edu.ua/uk/kafedra/personalni-storinki/162-dvornichenko-a-v)": "[Contact](https://pom.sumdu.edu.ua/en/department/personal-pages/167-dvornichenko-av)",
    "Файл видалено": "File removed",
    "Рисунок захищено": "Figure is protected",
    "Повідомлення надіслано": "Feedback sent",
    "Повідомлення": "Message",
    "за бажанням": "optional",
    "Надіслати" :"Send",
    "Повідомлення не може бути пустим": "Message cannot be empty",
    "Помилка надсилання": "Failed to send feedback",
    "Застосунок": "Application",
    "Вхід до системи": "Login",
    "Зворотний зв\'язок": "Feedback",
    "Логін": "Username",
    "Пароль": "Password",
    "Увійти": "Login",
    "Невірний логін або пароль": "Incorrect username or password",
    "🚪 Вийти": "🚪 Logout",
    "Користувач": "User",
    "Роль": "Role",
    "Статистичний аналіз, Фізика поверхні, Data Science": "Statistical analysis, Surface science, Data Science",
    "Вхідні дані": "Input data",
    "Завантажте файл": "Upload file",
    "Калібрування": "Calibration",
    "Реальна ширина зображення (нм)": "Actual image width (nm)",
    "Реальна висота структур (нм)": "Actual height of structures (nm)",
    "Масштаб": "Scale",
    "нм/пікс": "nm/px",
    "Структура даних": "Data structure",
    "Обрізати знизу, %": "Crop from the bottom, %",
    "Обрізане зображення": "Cropped image",
    "Кадрування зображення": "Cropping the image",
    "Оригінальне зображення": "Original image",
    "Параметри": "Settings",
    "Зверху (%)": "Top (%)",
    "Знизу (%)": "Bottom (%)",
    "Зліва (%)": "Left (%)",
    "Справа (%)": "Right (%)",
    "Тип структур": "Type of structures",
    "острівці": "dots",
    "отвори": "holes",
    "Зображення в градаціях сірого": "Gray-scale image",
    "Інвертувати зображення": "Invert image",
    "Аналізувати": "Analyze",
    "Середнє значення висоти <h₀>": "Mean height value  <h₀>",
    "Повний перепад висот (нм)": "Total height difference (nm)",
    "Середнє значення висоти поверхні (нм)": "Mean height value (nm)",
    "Найвищий пік над середнім рівнем (нм)": "Highest peak above the average leve (nm)",
    "Найглибша яма під середнім рівнем (нм)": "Deepest pit below the average level (nm)",
    "Середня шорсткість поверхні (нм)": "Average surface roughness (nm)",
    "RMS-шорсткість (нм)": "RMS-roughness (nm)",
    "Skewness (асиметрія)": "Skewness",
    "Kurtosis (гострота розподілу)": "Kurtosis",
    "Діапазон висот (нм)": "Height range (nm)",
    "Частота зустрічання": "Occurrence frequency",
    "Gaussian fit не зійшовся": "Gaussian fit did not converge",
    "Log-Normal fit не зійшовся": "Log-Normal fit did not converge",
    "Параметри шорсткості поверхні (ISO Roughness)": "Surface roughness parameters (ISO Roughness)",
    "Параметр": "Parameter",
    "Значення": "Value",
    "Завантажити дані у текстовий файл": "Download data into text file",
    "Дані": "Data",
    "Розподіл висот": "Height distribution",
    "Показати середню висоту": "Show mean height",
    "Показати Gaussian fit": "Show Gaussian fit",
    "Показати Log-Normal fit": "Show Log-Normal fit",
    "Завантажити дані": "Download data",
    "Аналіз кількості/розмірів структур на різних висотах": "Height-dependent analysis of the number and size of structures",
    "Мінімальна висота (нм)": "Minimal height (nm)",
    "Максимальна висота (нм)": "Max height (nm)",
    "Крок (нм)": "Step (nm)",
    "Логарифмічна шкала розмірів": "Logarithmic scale for sizes",
    "Кількість структур": "Number of structures",
    "Густина структур": "Number density",
    "(шт)": "(count)",
    "(см⁻²)": "(cm⁻²)",
    "Мінімальна висота має бути меншою за максимальну": "Minimal height should be less than maximal height",
    "Залежність кількості структур та середнього розміру від порогу висоти поверхні": "Dependence of structure count and mean size on height threshold",
    "Запустити тест": "Run test",
    "Розрахунок завершено": "Calculation completed",
    "Оптимальне значення висоти h₀": "Optimal height h₀",
    "Кількість структур": "Number of structures",
    "Висота поверхні (нм)": "Height of the surface (nm)",
    "Середній розмір структур (нм)": "Mean size of structures (nm)",
    "Завантажити всі дані у ZIP файл": "Download all data into ZIP file",
    "Сегментація та фільтрація": "Segmentation & Filtering",
    "Встановити поріг висоти h₀": "Set height threshold h₀",
    "Поріг h₀": "Height threshold h₀",
    "Ігнорувати малі структури": "Ignore small structures",
    "Мінімальний діаметр (нм)": "Minimal diameter (nm)",
    "Ігнорувати великі структури": "Ignore large structures",
    "Максимальний діаметр (нм)": "Maximal diameter (nm)",
    "Ігнорувати структури на границях": "Ignore structures at borders",
    "Застосувати періодичні граничні умови": "Apply periodic boundary conditions",
    "Обробка меж:": "Boundary conditions:",
    "Обробка меж: ": "Boundary conditions: ",
    "Без обробки": "Keep original",
    "Почати аналіз": "Start analysis",
    "Аналіз успішно завершено": "Analysis successfully completed",
    "Структури не знайдені": "No structures identified",
    "Відфільтроване зображення": "Filtered image",
    "структур ідентифіковано": "structures were identified",
    "Завантажити зображення": "Download image",
    "Статистичні характеристики структур на висоті h₀": "Statistical characteristics of structures at height h₀",
    "Завантажити дані у CSV файл": "Download data to CSV file",
    "Завантажити дані у TXT файл": "Download data to TXT file",
    "Графічний Аналіз": "Graphical Analysis",
    "Розподіли розмірів": "Size distributions",
    "Геометрія структур": "Geometry of structures",
    "Розподіл відстаней": "Distance distributions",
    "Кластеризація": "ML Clustering",
    "Сформувати звіт": "Generate report",
    "Кількість бінів для розподілів": "Number of bins for distributions",
    "Формат геометричної характеристики": "Geometrical characteristic format",
    "Густина структур (см⁻²)": "Surface density of structures (cm⁻²)",
    "Залежність густини структур від площі": "Dependence of density of structures on area",
    "Залежність густини структур від діаметра": "Dependence of density of structures on diameter",
    "Залежність густини структур від периметра": "Dependence of density of structures on perimeter",
    "Залежність густини структур від коефіцієнта округлості": "Dependence of density of structures on circularity",
    "Залежність густини структур від коефіцієнта витягнутості": "Dependence of density of structures on aspect ratio",
    "Залежність густини структур від довжини великої вісі еліпса": "Dependence of density of structures on major axis length",
    "Залежність густини структур від довжини малої вісі еліпса": "Dependence of density of structures on minor axis length",
    "Залежність густини структур від кута повороту еліпса": "Dependence of density of structures on ellipse angle",
    "Розподіл структур за площею": "Distribution by area",
    "Розподіл структур за діаметром": "Distribution by diameter",
    "Розподіл структур за периметром": "Distribution by perimeter",
    "Розподіл структур за розмірами (площею)": "Size distribution by area",
    "Розподіл структур за розмірами (діаметром)": "Size distribution by diameter",
    "Розподіл структур за розмірами (периметром)": "Size distribution by perimeter",
    "Розподіл структур за коефіцієнтом округлості": "Distribution by circularity",
    "Розподіл структур за коефіцієнтом витягнутості": "Distribution by aspect ratio",
    "Розподіл структур за довжиною великої вісі еліпса": "Distribution by major axis length",
    "Розподіл структур за довжиною малої вісі еліпса": "Distribution by minor axis length",
    "Розподіл структур за кутом повороту еліпса": "Distribution by ellipse angle",
    "Розподіл найближчих міжцентрових відстаней між структурами": "Distribution of nearest neighbor distances",
    "Розподіл відстаней між межами структур": "Distribution of edge-to-edge distances",
    "Дані: Індекс Кларка-Еванса": "Data: Clark-Evans Index",
    "Кількість кластерів": "Number of clusters",
    "Провести кластеризацію": "Make clusterization",
    "Зв’язки між розміром структур, коефіцієнтом округлості та кутом нахилу еліпса": "Relationships between structure size, circularity, and ellipse orientation angle",
    "Завантажити Pairplot": "Download Pairplot",
    "Розподіл даних у різних групах": "Data distribution in different groups",
    "Параметр": "Parameter",
    "Кластери структур за розмірами": "Clustering of structures by size",
    "Завантажити Violinplot": "Download Violinplot",
    "Площа (нм²)": "Area (nm²)",
    "Діаметр (нм)": "Diameter (nm)",
    "Периметр (нм)": "Perimeter (nm)",
    "Коефцієнт окуглості": "Circularity coefficient",
    "Довжина великої вісі еліпса (нм)": "Length of major axis of ellipse (nm)",
    "Довжина малої вісі еліпса (нм)": "Length of minor axis of ellipse (nm)",
    "Коефіцієнт витягнутості": "Aspect ratio",
    "Кут повороту еліпса (°)": "Angle of ellipse (°)",
    "Найближча міжцентрова відстань (нм)": "Nearest neighbour distance (nm)",
    "Відстань між межами структур (нм)": "Edge-to-edge distance (nm)",
    "Показати середнє значення": "Show mean value",
    "Формат розмірів": "Sizes format",
    "Без перетворень": "Keep nontransformed",
    "Логарифмічне перетворення": "Log₁₀ transformation",
    "Тип гістограми": "Type of histogram",
    "Нормований розподіл": "Normalized distribution",
    "Густина структур": "Density of structures",
    "Показати розподіли розмірів": "Show distributions by sizes",
    "Зробити ZIP архів з даними": "Make ZIP file with data",
    "Кількість структур": "Number of structures",
    "Середній розмір структур (нм)": "Mean structure size (nm)",
    "Площа (нм²)": "Area (nm²)",
    "Густина, (см⁻²)": "Number density (cm⁻²)",
    "Коефіцієнт округлості": "Circularity",
    "Коеф. варіації (%)": "Coef. Var. (%)",
    "Середнє": "Mean",
    "Медіана": "Median",
    "Мінімальне": "Minimum",
    "Максимальне": "Maximum",
    "Дисперсія": "St. Dev.",
    "Висота від h₀ (нм)": "Height from h₀ (nm)",

    "Формування звіту за результатами аналізу зображення": "Generating a report based on the analysis results of image",
    "Згенерувати ZIP архів для LaTeX": "Generate ZIP archive for LaTeX",
    "Згенерувати PDF звіту": "Generate PDF of report",
    "Завантажити звіт у форматі PDF": "Download report in PDF formate"
}


roughness_ua = {
    "Heights_difference": "Повний перепад висот (нм)",
    "Mean_height": "Середнє значення висоти поверхні (нм)",
    "Max_height": "Найвищий пік над середнім рівнем (нм)",
    "Min_height": "Найглибша яма під середнім рівнем (нм)",
    "Mean_roughness": "Середня шорсткість поверхні (нм)",
    "RMS-roughness": "RMS-шорсткість (нм)",
    "Skewness": "Skewness (асиметрія розподілу)",
    "Kurtosis": "Kurtosis (гострота розподілу)"
}

roughness_en = {
    "Heights_difference": "Total height difference (nm)",
    "Mean_height": "Mean height value (nm)",
    "Max_height": "Highest peak above the average level (nm)",
    "Min_height": "Deepest pit below the average level (nm)",
    "Mean_roughness": "Average surface roughness (nm)",
    "RMS-roughness": "RMS-roughness (nm)",
    "Skewness": "Skewness",
    "Kurtosis": "Kurtosis"
}

cols_ua = {
    "Area (nm^2)": "Площа (нм²)",
    "Diameter (nm)": "Діаметр (нм)",
    "Perimeter (nm)": "Периметр (нм)",
    "Circularity": "Коефцієнт куглості",
    "Major axis of elips (nm)": "Велика вісь еліпса (нм)",
    "Minor axis of elips (nm)": "Мала вісь еліпса (нм)",
    "Aspect Ratio": "Співвідношення осей",
    "Angle of elips": "Кут повороту еліпса (°)",
    "Height from h₀ (nm)": "Висота від h₀ (нм)",
    "Nearest Neighbor (nm)": "Найближча міжцентрова відстань (нм)",
    "Edge Distance (nm)": "Відстань між межами структур (нм)"
}

cols_en = {
    "Area (nm^2)": "Area (nm²)",
    "Diameter (nm)": "Diameter (nm)",
    "Perimeter (nm)": "Perimeter (nm)",
    "Circularity": "Circularity coefficient",
    "Major axis of elips (nm)": "Major axis of ellipse (nm)",
    "Minor axis of elips (nm)": "Minor axis of ellipse (nm)",
    "Aspect Ratio": "Aspect ratio",
    "Angle of elips": "Angle of ellipse (°)",
    "Height from h₀ (nm)": "Height from h₀ (nm)",
    "Nearest Neighbor (nm)": "Nearest neighbour distance (nm)",
    "Edge Distance (nm)": "Edge-to-edge distance (nm)"
}

labels_ua = {
    'Diameter (nm)': 'Розмір структур (нм)',
    'Circularity': 'Коефіцієнт округлості',
    'Label': 'Тип структури',
    'Angle of elips': 'Кут повороту еліпса'
}

labels_en = {
    'Diameter (nm)': 'Size of structures (nm)',
    'Circularity': 'Circularity coefficient',
    'Label': 'Type of structures',
    'Angle of elips': 'Angle of ellipse'
}

size_ua = {
    "Small": "Малі",
    "Medium": "Середні",
    "Large": "Великі",
    "X-Large": "Дуже великі",
    "XX-Large": "Надвеликі"
}

size_en = {
    "Small": "Small",
    "Medium": "Medium",
    "Large": "Large",
    "X-Large": "X-Large",
    "XX-Large": "XX-Large"
}